from Incentives import Incentives

"""
incentives = Incentives(
    IN_BOMB_RANGE_PENALTY=-5,
    NOT_IN_BOMB_RANGE_PENALTY=5,
    MOVING_INTO_BOMB_RANGE_PENALTY=-10,
    MOVING_FROM_BOMB_RANGE_REWARD=10,
    NOT_MOVING_FROM_BOMB_RANGE_PENALTY=-10,
    WAITING_BESIDE_BOMB_RANGE_REWARD=100,
    TRYING_TO_ENTER_WALL_PENALTY=-5,
    BOXES_IN_BOMB_RANGE_REWARD=10,
    WALK_INTO_SPACE_REWARD=5,
    SAME_GRID_PENALTY=-5,
    TRAPPED_WITH_BOMB_PENALTY=-10,
    NOT_IN_BOMB_RANGE_REWARD = 1,
    DEATH_PENALTY=-100
)
"""

incentives = Incentives(
    DEATH_PENALTY=-100,
    DESTROY_BOX_REWARD=1,
    DESTROY_ENEMY_REWARD=100
)
