from Incentives import Incentives

incentives = Incentives(
    DEATH_PENALTY=-100,
    DESTROY_BOX_REWARD=1,
    DESTROY_ENEMY_REWARD=100,
    TRAPPED_THEMSELVES_GUARANTEED_DEATH=-200,
    STAY_ALIVE=0.001,
    PUT_BOMB_HAVE_ESCAPE_ROUTE_REWARD = 100,
    PUT_BOMB_NO_ESCAPE_ROUTE_PENALTY = -100,
    MOVING_INTO_BOMB_RANGE_PENALTY = -10,
    MOVING_FROM_BOMB_RANGE_REWARD = 10,
    NOT_MOVING_FROM_BOMB_RANGE_PENALTY = -10,
    WAITING_BESIDE_BOMB_RANGE_REWARD = 100,
    TRAPPED_WITH_BOMB_PENALTY = -10,
)