from Incentives import Incentives

incentives = Incentives(
    PUT_BOMB_HAVE_ESCAPE_ROUTE_REWARD = 100,
    PUT_BOMB_NO_ESCAPE_ROUTE_PENALTY = -100,
    MOVING_INTO_BOMB_RANGE_PENALTY = -10,
    MOVING_FROM_BOMB_RANGE_REWARD = 10,
    NOT_MOVING_FROM_BOMB_RANGE_PENALTY = -10,
    WAITING_BESIDE_BOMB_RANGE_REWARD = 100,
    TRAPPED_WITH_BOMB_PENALTY = -10,
    NOT_IN_BOMB_RANGE_REWARD = 1,
    DEATH_PENALTY=-1000,
    DESTROY_BOX_REWARD=100,
    DESTROY_ENEMY_REWARD=100
)